name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH & Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Pulling latest code..."
            cd /home/ec2-user/nextwithnest
            git reset --hard
            git clean -fd
            git pull origin main

            echo "Rebuilding Docker containers..."
            docker-compose down
            docker-compose up -d --build

            echo "Deployment complete."
